name: Update IP List

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次
  workflow_dispatch: # 允许手动触发
  push: # 允许提交触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/avotccom@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        
    - name: Run script
      run: python ${{ github.workspace }}/yxip.py
        
    - name: Commit and push changes
      run: |
        git config --global user.email "avotc@gmail.com"
        git config --global user.name "avotc"
        if [ -n "$(git status --token)" ]; then
          git add ip.txt
          git commit -m "Automatic update"
          git push
        else
          echo "执行失败."
        fi
