name: Update IP List

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次
  workflow_dispatch: # 允许手动触发
  push: # 允许提交触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    permissions:  # 添加权限声明
      contents: write  # 授予写入权限

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run script
      run: python yxip.py
        
    - name: Commit and push changes
      run: |
        # 设置本地git配置（非全局）
        git config user.email "avotc@gmail.com"
        git config user.name "avotc"
        
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt
          git commit -m "Automatic update"
          
          # 使用认证URL推送
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
        else
          echo "没有文件变更，跳过提交"
        fi
