name: Update IP List

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次
  workflow_dispatch: # 允许手动触发
  push: # 允许提交触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GIT_EMAIL: "avotc@gmail.com"
      GIT_NAME: "avotc"
      TARGET_BRANCH: "main"

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}  # 关键修复：添加token参数

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run script
      run: python yxip.py
        
    - name: Commit and push changes
      run: |
        # 使用局部配置（非全局）
        git config user.email "${{ env.GIT_EMAIL }}"
        git config user.name "${{ env.GIT_NAME }}"
        
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt
          git commit -m "Automatic update"
          
          # 使用认证URL推送（关键修复）
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ env.TARGET_BRANCH }}
        else
          echo "没有文件变更，跳过提交"
        fi
